### ISSUE TITLE
Default `--filepath`

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#10]
I think it's worth mentioning the default filepath for submitting - just to the task place in repo, e.g.
```bash
resources/fashion_mnist/problems/task1.ipynb
```
for task 1 from fashion mnist. In this way we get rid of a redundant parameter in the command line.

**Comment by jakubczakon** [comment]
Changed. Waiting for PR

**Comment by kamil-kaczmarek** [comment]
@buus2 done.
