### ISSUE TITLE
Changing run_minerva.py and config.yaml to default Neptune names

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#12]
I suggest to consider changing names:
- `run_minerva.py` -> `main.py`,
- `config.yaml` -> `neptune.yaml`.
In this way you can shorten neptune commands, eg. from
```bash
neptune run run_minerva.py --config config.yaml -- dry_run --problem fashion_mnist
```
to
```bash
neptune run -- dry_run --problem fashion_mnist
```

**Comment by jakubczakon** [comment]
Changed. Waiting for PR

**Comment by kamil-kaczmarek** [comment]
@buus2, merged with `Feature request 10 11 12 `
