### ISSUE TITLE
Where are data for whales project?

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#15]
As above.

**Comment by kamil-kaczmarek** [comment]
Hi @buus2 
1. If you work on Neptune cloud, the data is already uploaded to the cloud (public directory).
2. If you work locally you need to download the data directly from Kaggle. In the future we will have cloud storage for the data.

Thanks for pointing this out: we need to add appropriate description on how to get whales data.

**Comment by kamil-kaczmarek** [comment]
@buus2 You also may want to consult your `config.yaml` for data directories.
