### ISSUE TITLE
Is --subproblem parameter really needed?

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#20]
Each single step in whales constantly belongs to exactly one sub problem. So why should user care about sub problem by typing `--sub_problem sth` in command line? I think the sub problem could be inferred from the task automatically, eventually user could have a possibility (not an obligation) to choose one in dry dun mode.

**Comment by jakubczakon** [comment]
added subproblem inference. Waiting for PR to merge

**Comment by kamil-kaczmarek** [comment]
@buus2 merged
