### ISSUE TITLE
Neptune: logs created with use of `logging` go to Neptune stderr

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#22]
If you use Neptune, logs created with use of `logging` go to Neptune stderr, not to stdout.

I also checked that if you change `logger.setLevel` from `logging.INFO` (equal 20) to:
- 19: nothing changes,
- 21: logs from `logging` are not displayed anywhere.

**Comment by jakubczakon** [comment]
I think this is a neptune related bug so I contacted neptune team on their community forum here:
https://community.neptune.ml/t/outputs-from-logging-end-up-in-the-stderr-channel/218

I will fix it as soon as I get the information from them.

**Comment by jakubczakon** [comment]
It turns out that logging by default logs to stderr and you need to redirected to stdout if you want to.

It is done now, and waiting for the PR to merge.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon @buus2 
Merged
