### ISSUE TITLE
Avoid empty solution functions unless necessary

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#24]
In some tasks we have to do nothing with `solution` function, however we can still see this empty function. I'd like to suggest to just erase this function (or, analogously, `CONFIG`), unless necessary.

**Comment by kamil-kaczmarek** [comment]
@buus2 @jakubczakon As far as I understand this is related to the `solution` function in the notebooks, correct?

**Comment by buus2** [comment]
Correct.

**Comment by jakubczakon** [comment]
Done and waiting for PR to merge.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon @buus2 
Done.
