### ISSUE TITLE
Relatively high entry treshold in task 1 in fashion mnist

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#26]
I think some inexperienced users may encounter some difficulties in the first task of the first problem they see (Task 1 of fashion mnist).
- If you don't know DL then you won't learn it from that task and you won't obtain any clues how and where to start.
- If you know DL, but don't know Keras, then you'll have a hard time trying to learn it from that task and, for instance, you may end up struggling with writing down the model in the sequential regime whereas the functional one is required there.

One can give similar notes to the other tasks.

Generally, I think that adding some additional comments for newbies would broaden the potential Minerva's target with little effort.

**Comment by buus2** [comment]
New wiki page "First steps in deep learning" is now added. I think that this is enough. I suggest to close the thread.
@kamil-kaczmarek

**Comment by kamil-kaczmarek** [comment]
@buus2 Fully agree. [First steps](https://github.com/neptune-ml/minerva/wiki/First-steps-in-deep-learning) are also mentioned in the notebooks, so we have nice linking between task and Wiki contents. Thanks!
