### ISSUE TITLE
train_mode=False in dry_run mode

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#37]
I strongly suggest to set default `train_mode` as `False` in `dry_run` mode. In this way the user by default can quickly check if everything (including paths to original solutions) works. However, in my opinion `train_mode=True` should remain as possible to set to allow users to re-train their solutions and save them in their favourite path.

**Comment by jakubczakon** [comment]
I went with the option specified in issue #39 

It is changed now, waiting for PR to merge.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon @buus2 we do `dry_train` and `dry_eval`. Merged #42
