### ISSUE TITLE
dry_train and dry_eval?

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#39]
I propose to exchange:
- `dry_run train_mode=False` by `dry_eval`,
- `dry_run train_mode=True` by `dry_train`.

In this way, the user could consciously choose if:
- he/she wants to only evaluate results from in-house solution to quickly check if everything (including paths to solutions and data) is set correctly,
- he/she wants to spend a lot of time to re-train the in-house solution and save it in his/her favourite path.

Also, after these exchanges the readmes should become more understandable.

Alternatively, I propose to exchange `train_mode` with `only_eval`/`eval_only`.

**Comment by jakubczakon** [comment]
I like the idea of two options.

It is changed now, waiting for PR to merge.

**Comment by kamil-kaczmarek** [comment]
@buus2 @jakubczakon merged (#42 )
