### ISSUE TITLE
what's the difference between dry_train and dry_eval?

### ISSUE THREAD

**Issue by buus2** [neptune-ml/minerva#45]
For `fashion_mnist` problem, if you set `solution_dir` already contained the trained model then the training in the `dry_train` mode takes only one epoch. Thus, `dry_train` and `dry_eval` do the same and there is no need to distinguish them.

**Comment by jakubczakon** [comment]
Done, waiting for PR to merge.

**Comment by kamil-kaczmarek** [comment]
@jakubczakon @buus2 #50
